import Head from 'next/head';
import { useEffect } from 'react';
import { useDispatch} from 'react-redux';
import clientPromise from '../lib/mongodb';
import { useSession } from "next-auth/react";
import Layout from '../components/layout/layout';
import { addUser } from '../components/store/reducers/userReducer';
import LandingLayout from "../components/landingLayout/landingLayout";
import { addData } from '../components/store/reducers/productReducer';
import CategoriesLayout from '../components/Categories/categoriesLayout/categoriesLayout';
import CheckoutFooterLayout from '../components/checkoutFooterLayout/checkoutFooterLayout';
import FeaturedCategoriesLayout from '../components/FeaturedCategories/featuredCategoriesLayout/featuredCategoiresLayout';

const Home = (props) => {
  const dispatch = useDispatch();
  const {data: session} = useSession();

  useEffect(() => {
    dispatch(addData({data: JSON.parse(props.products)}));
    console.log(props.userResult);
    // dispatch(addUser({data: JSON.parse(props.userResult)}));
  })

  return (
    <Layout>
      <Head>
        <title>OneHowl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingLayout />
      <FeaturedCategoriesLayout data={props.products} title="Featured Categories" titleId="fc" />
      <CategoriesLayout data={props.products} titleId="fc" />
      <CheckoutFooterLayout />
    </Layout>
  )
}

export const getStaticProps = async () => {
  const client = await clientPromise;
  const database = client.db(process.env.MONGO_DB);
  const productCollection = database.collection("productCollection");
  const userCollection = database.collection("userCollection");
  const productResult = await productCollection.find({}).toArray();
  const userResult = await productCollection.findOne({_id: "anujchhabra1901@gmail.com"});
  return {
    props: {
      products: JSON.stringify(productResult),
      user: JSON.stringify(userResult)
    }
  }
}


export default Home;


